spring:
  profiles:
    active: -dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-zjk-dev
    
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-zjk-test